from .attention_reference import (
    explicit_dequantized_attention,
    mix_page_ref,
    run_attention_reference,
    score_page_ref,
)
from .attention_runtime import decode_step, mix_page, prepare_page, prepare_pages, score_page
from .config import DotCacheConfig
from .page_cache import PreparedPageCache
from .encode import encode_page
from .planner import choose_mode
from .session_runtime import PagedDecodeSession
from .tracing import ExecutionTrace
from .types import EncodedPage, PageHeader
from .model_kv_cache import ModelPagedKVCache
from .kv_quant_registry import KvQuantBaselineSpec, get_kv_quant_baseline, list_kv_quant_baselines
from .model_registry import ModelSpec, get_model_spec, list_model_specs
from .planner import LayerPolicy, PageModeSpec, PageStats, choose_page_mode, observe_page
from .state_cache_sim import (
    StateAblationResult,
    StateLayerRecord,
    StateSimResult,
    StateTileSpec,
    simulate_state_codec,
    simulate_state_sequence,
)

__all__ = [
    "DotCacheConfig",
    "EncodedPage",
    "ExecutionTrace",
    "KvQuantBaselineSpec",
    "LayerPolicy",
    "ModelSpec",
    "ModelPagedKVCache",
    "PageModeSpec",
    "PageStats",
    "PageHeader",
    "PagedDecodeSession",
    "PreparedPageCache",
    "StateAblationResult",
    "StateLayerRecord",
    "StateSimResult",
    "StateTileSpec",
    "choose_mode",
    "choose_page_mode",
    "decode_step",
    "encode_page",
    "explicit_dequantized_attention",
    "get_kv_quant_baseline",
    "get_model_spec",
    "list_model_specs",
    "list_kv_quant_baselines",
    "mix_page",
    "mix_page_ref",
    "prepare_page",
    "prepare_pages",
    "run_attention_reference",
    "score_page",
    "score_page_ref",
    "simulate_state_codec",
    "simulate_state_sequence",
    "observe_page",
]

try:  # pragma: no cover - optional HF path
    from .integrations import (
        LlamaDotCacheHarness,
        LlamaDotCacheModelAdapter,
        LlamaReplayRecord,
        Qwen2DotCacheHarness,
        Qwen2DotCacheModelAdapter,
        Qwen35AttentionSubsetDotCacheHarness,
        Qwen35AttentionSubsetDotCacheModelAdapter,
        Qwen35AttentionSubsetHarness,
        Qwen35AttentionSubsetModelAdapter,
        Qwen35DeltaNetStateHarness,
        Qwen35DeltaNetStateModelAdapter,
        Qwen35TextHarness,
        Qwen35TextModelAdapter,
        VllmAdapterConfig,
        VllmDotCacheModelAdapter,
        VllmPagedKVCache,
        VLLM_V1_MULTIPROCESSING_ENV,
        configure_vllm_inprocess_runtime,
        get_vllm_version,
        install_dotcache_on_vllm_model,
        install_dotcache_on_vllm_runtime,
        require_supported_vllm_version,
        inspect_qwen35_deltanet_state,
        inspect_qwen35_hybrid_state,
        load_qwen35_text_only_from_pretrained,
        run_qwen35_attention_subset_prefill_ablation_harness,
        run_qwen35_attention_subset_dotcache_harness,
        run_qwen35_attention_subset_replay_harness,
        run_qwen35_deltanet_state_ablation_harness,
        run_llama_generation_harness,
        run_llama_replay_harness,
        run_qwen2_generation_harness,
        run_qwen2_loss_harness,
        run_qwen2_replay_harness,
        run_qwen35_text_generation_harness,
        run_qwen35_text_loss_harness,
        summarize_qwen35_dotcache_fit,
        summarize_qwen35_hybrid_state,
        transformers_available,
        vllm_available,
    )
except ImportError:  # pragma: no cover - exercised when optional deps are absent
    pass
else:
    __all__.extend(
        [
            "LlamaDotCacheHarness",
            "LlamaDotCacheModelAdapter",
            "LlamaReplayRecord",
            "Qwen2DotCacheHarness",
            "Qwen2DotCacheModelAdapter",
            "Qwen35AttentionSubsetDotCacheHarness",
            "Qwen35AttentionSubsetDotCacheModelAdapter",
            "Qwen35AttentionSubsetHarness",
            "Qwen35AttentionSubsetModelAdapter",
            "Qwen35DeltaNetStateHarness",
            "Qwen35DeltaNetStateModelAdapter",
            "Qwen35TextHarness",
            "Qwen35TextModelAdapter",
            "VllmAdapterConfig",
            "VllmDotCacheModelAdapter",
            "VllmPagedKVCache",
            "VLLM_V1_MULTIPROCESSING_ENV",
            "configure_vllm_inprocess_runtime",
            "get_vllm_version",
            "install_dotcache_on_vllm_model",
            "install_dotcache_on_vllm_runtime",
            "require_supported_vllm_version",
            "inspect_qwen35_deltanet_state",
            "inspect_qwen35_hybrid_state",
            "load_qwen35_text_only_from_pretrained",
            "run_qwen35_attention_subset_prefill_ablation_harness",
            "run_qwen35_attention_subset_dotcache_harness",
            "run_qwen35_attention_subset_replay_harness",
            "run_qwen35_deltanet_state_ablation_harness",
            "run_llama_generation_harness",
            "run_llama_replay_harness",
            "run_qwen2_generation_harness",
            "run_qwen2_loss_harness",
            "run_qwen2_replay_harness",
            "run_qwen35_text_generation_harness",
            "run_qwen35_text_loss_harness",
            "summarize_qwen35_dotcache_fit",
            "summarize_qwen35_hybrid_state",
            "transformers_available",
            "vllm_available",
        ]
    )
