#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from dotcache.selector_baselines import (
    load_selector_candidate_examples,
    load_selector_examples,
    load_selector_split_examples,
    run_selector_baseline_bakeoff,
    run_selector_fixed_split_bakeoff,
    run_selector_leave_prompt_family_layer_out_bakeoff,
    run_selector_leave_prompt_family_out_bakeoff,
    run_selector_leave_prompt_variant_out_bakeoff,
    run_selector_leave_layer_out_bakeoff,
    run_selector_multiseed_bakeoff,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train and evaluate simple page-selector baselines against oracle labels.")
    parser.add_argument("--split-dir", default=None, help="Optional frozen split directory containing train/ and test/ subdirectories.")
    parser.add_argument("--labels", default=None, help="Path to labels.jsonl generated by generate_page_oracle_labels.py.")
    parser.add_argument("--selector-dataset", default=None, help="Path to selector_dataset.jsonl generated by generate_page_oracle_labels.py.")
    parser.add_argument("--selector-candidate-dataset", default=None, help="Optional path to selector_candidate_dataset.jsonl for candidate-aware baselines.")
    parser.add_argument("--output-dir", required=True, help="Directory where baseline summaries and predictions should be written.")
    parser.add_argument("--evaluation-mode", choices=["single", "multiseed", "leave-layer-out", "leave-family-out", "leave-variant-out", "leave-family-layer-out", "all"], default="single")
    parser.add_argument("--test-fraction", type=float, default=0.25)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--seeds", default=None, help="Comma-separated seed list for multiseed evaluation. Defaults to seed,seed+1,seed+2.")
    parser.add_argument("--linear-steps", type=int, default=400)
    parser.add_argument("--linear-learning-rate", type=float, default=0.2)
    parser.add_argument("--linear-l2", type=float, default=1e-3)
    return parser.parse_args()


def _write_prediction_block(handle, results: dict[str, dict], *, evaluation_name: str, fold_name: str) -> None:
    for baseline_name, summary in results.items():
        for prediction in summary.get("predictions", []):
            handle.write(
                json.dumps(
                    {
                        "evaluation_name": evaluation_name,
                        "fold_name": fold_name,
                        "baseline": baseline_name,
                        **prediction,
                    },
                    sort_keys=True,
                )
                + "\n"
            )


def main() -> int:
    args = parse_args()
    if args.split_dir is not None:
        if args.evaluation_mode != "single":
            raise SystemExit("--split-dir currently supports only --evaluation-mode single")
        split_payload = load_selector_split_examples(split_dir=args.split_dir)
        payload = run_selector_fixed_split_bakeoff(
            train_examples=split_payload["train_examples"],
            test_examples=split_payload["test_examples"],
            train_candidate_examples=split_payload["train_candidate_examples"],
            test_candidate_examples=split_payload["test_candidate_examples"],
            linear_steps=args.linear_steps,
            linear_learning_rate=args.linear_learning_rate,
            linear_l2=args.linear_l2,
            split_metadata={} if split_payload["split_summary"] is None else split_payload["split_summary"],
        )
    else:
        if args.labels is None or args.selector_dataset is None:
            raise SystemExit("--labels and --selector-dataset are required unless --split-dir is provided")
        examples = load_selector_examples(
            labels_path=args.labels,
            selector_dataset_path=args.selector_dataset,
        )
        candidate_examples = (
            None
            if args.selector_candidate_dataset is None
            else load_selector_candidate_examples(selector_candidate_dataset_path=args.selector_candidate_dataset)
        )
        payload = run_selector_baseline_bakeoff(
            examples,
            candidate_examples=candidate_examples,
            test_fraction=args.test_fraction,
            seed=args.seed,
            linear_steps=args.linear_steps,
            linear_learning_rate=args.linear_learning_rate,
            linear_l2=args.linear_l2,
        )
        multiseed_seeds = (
            [int(token.strip()) for token in args.seeds.split(",") if token.strip()]
            if args.seeds is not None
            else [int(args.seed), int(args.seed) + 1, int(args.seed) + 2]
        )
        if args.evaluation_mode in {"multiseed", "all"}:
            payload = {
                **payload,
                "multiseed": run_selector_multiseed_bakeoff(
                    examples,
                    candidate_examples=candidate_examples,
                    seeds=multiseed_seeds,
                    test_fraction=args.test_fraction,
                    linear_steps=args.linear_steps,
                    linear_learning_rate=args.linear_learning_rate,
                    linear_l2=args.linear_l2,
                ),
            }
        if args.evaluation_mode in {"leave-layer-out", "all"}:
            payload = {
                **payload,
                "leave_layer_out": run_selector_leave_layer_out_bakeoff(
                    examples,
                    candidate_examples=candidate_examples,
                    linear_steps=args.linear_steps,
                    linear_learning_rate=args.linear_learning_rate,
                    linear_l2=args.linear_l2,
                ),
            }
        if args.evaluation_mode in {"leave-family-out", "all"}:
            payload = {
                **payload,
                "leave_prompt_family_out": run_selector_leave_prompt_family_out_bakeoff(
                    examples,
                    candidate_examples=candidate_examples,
                    linear_steps=args.linear_steps,
                    linear_learning_rate=args.linear_learning_rate,
                    linear_l2=args.linear_l2,
                ),
            }
        if args.evaluation_mode in {"leave-variant-out", "all"}:
            payload = {
                **payload,
                "leave_prompt_variant_out": run_selector_leave_prompt_variant_out_bakeoff(
                    examples,
                    candidate_examples=candidate_examples,
                    linear_steps=args.linear_steps,
                    linear_learning_rate=args.linear_learning_rate,
                    linear_l2=args.linear_l2,
                ),
            }
        if args.evaluation_mode in {"leave-family-layer-out", "all"}:
            payload = {
                **payload,
                "leave_prompt_family_layer_out": run_selector_leave_prompt_family_layer_out_bakeoff(
                    examples,
                    candidate_examples=candidate_examples,
                    linear_steps=args.linear_steps,
                    linear_learning_rate=args.linear_learning_rate,
                    linear_l2=args.linear_l2,
                ),
            }

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    summary_path = output_dir / "selector_baseline_summary.json"
    markdown_path = output_dir / "selector_baseline_summary.md"
    predictions_path = output_dir / "selector_baseline_predictions.jsonl"

    summary_path.write_text(json.dumps(payload, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    markdown_sections = [str(payload["summary_markdown"])]
    if "multiseed" in payload:
        markdown_sections.append("")
        markdown_sections.append("## Multiseed")
        markdown_sections.append(str(payload["multiseed"]["summary_markdown"]))
    if "leave_layer_out" in payload:
        markdown_sections.append("")
        markdown_sections.append("## Leave Layer Out")
        markdown_sections.append(str(payload["leave_layer_out"]["summary_markdown"]))
    if "leave_prompt_family_out" in payload:
        markdown_sections.append("")
        markdown_sections.append("## Leave Prompt Family Out")
        markdown_sections.append(str(payload["leave_prompt_family_out"]["summary_markdown"]))
    if "leave_prompt_variant_out" in payload:
        markdown_sections.append("")
        markdown_sections.append("## Leave Prompt Variant Out")
        markdown_sections.append(str(payload["leave_prompt_variant_out"]["summary_markdown"]))
    if "leave_prompt_family_layer_out" in payload:
        markdown_sections.append("")
        markdown_sections.append("## Leave Prompt Family Layer Out")
        markdown_sections.append(str(payload["leave_prompt_family_layer_out"]["summary_markdown"]))
    markdown_path.write_text("\n".join(markdown_sections) + "\n", encoding="utf-8")
    with predictions_path.open("w", encoding="utf-8") as handle:
        _write_prediction_block(handle, payload["results"], evaluation_name="single", fold_name="seed")
        if "multiseed" in payload:
            for fold in payload["multiseed"]["folds"]:
                _write_prediction_block(handle, fold["results"], evaluation_name="multiseed", fold_name=str(fold["fold_name"]))
        if "leave_layer_out" in payload:
            for fold in payload["leave_layer_out"]["folds"]:
                _write_prediction_block(handle, fold["results"], evaluation_name="leave_layer_out", fold_name=str(fold["fold_name"]))
        if "leave_prompt_family_out" in payload:
            for fold in payload["leave_prompt_family_out"]["folds"]:
                _write_prediction_block(handle, fold["results"], evaluation_name="leave_prompt_family_out", fold_name=str(fold["fold_name"]))
        if "leave_prompt_variant_out" in payload:
            for fold in payload["leave_prompt_variant_out"]["folds"]:
                _write_prediction_block(handle, fold["results"], evaluation_name="leave_prompt_variant_out", fold_name=str(fold["fold_name"]))
        if "leave_prompt_family_layer_out" in payload:
            for fold in payload["leave_prompt_family_layer_out"]["folds"]:
                _write_prediction_block(handle, fold["results"], evaluation_name="leave_prompt_family_layer_out", fold_name=str(fold["fold_name"]))

    print(summary_path)
    print(markdown_path)
    print(predictions_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
