#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from dotcache.selector_baselines import (
    RUNTIME_SELECTOR_FEATURE_NAMES,
    calibrate_selector_logit_offset,
    evaluate_candidate_safe_router_model,
    evaluate_selector_model,
    load_selector_candidate_examples,
    load_selector_examples,
    load_selector_split_examples,
    save_page_selector_artifact,
    train_candidate_safe_router,
    train_runtime_linear_selector,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a runtime-safe learned page-selector artifact for serving.")
    parser.add_argument(
        "--split-dir",
        default=None,
        help="Optional frozen split directory containing train/ and test/ bundles. If provided, trains on train/ and evaluates on test/.",
    )
    parser.add_argument("--labels", default=None, help="Path to labels.jsonl generated by generate_page_oracle_labels.py.")
    parser.add_argument(
        "--selector-dataset",
        default=None,
        help="Path to selector_dataset.jsonl generated by generate_page_oracle_labels.py.",
    )
    parser.add_argument(
        "--selector-candidate-dataset",
        default=None,
        help="Path to selector_candidate_dataset.jsonl generated by generate_page_oracle_labels.py. Required for candidate-safe-router artifacts.",
    )
    parser.add_argument("--output-dir", required=True, help="Directory where the selector artifact and summaries should be written.")
    parser.add_argument(
        "--artifact-kind",
        choices=["linear", "candidate-safe-router"],
        default="linear",
        help="Artifact type to train for serving.",
    )
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--learning-rate", type=float, default=0.2)
    parser.add_argument("--l2", type=float, default=1e-3)
    parser.add_argument(
        "--class-balance",
        type=float,
        default=0.5,
        help="Exponent for inverse-frequency class reweighting during selector training.",
    )
    parser.add_argument(
        "--safe-bytes-weight",
        type=float,
        default=1.0,
        help="Extra training weight applied to rows whose cheapest safe candidate is materially cheaper than the high-fidelity reference candidate.",
    )
    parser.add_argument(
        "--unsafe-error-weight",
        type=float,
        default=0.5,
        help="Extra training penalty applied to probability mass placed on candidates that are unsafe for a row.",
    )
    parser.add_argument(
        "--reference-candidate",
        default="M3/affine/4/float16",
        help="High-fidelity reference candidate used when computing compression-aware training weights.",
    )
    parser.add_argument(
        "--calibration-target-candidate",
        default="M3/affine/4/float16",
        help="Candidate whose logit should be swept on held-out data to find a compression/exactness operating point.",
    )
    parser.add_argument(
        "--calibration-offsets",
        type=float,
        nargs="*",
        default=[-1.5, -1.0, -0.5, 0.0, 0.5, 1.0, 1.5],
        help="Held-out logit offsets to evaluate for the calibration target candidate.",
    )
    parser.add_argument(
        "--calibration-min-target-accuracy",
        type=float,
        default=0.999,
        help="Minimum held-out target accuracy required for a calibrated operating point to be considered feasible.",
    )
    parser.add_argument(
        "--calibration-min-safe-prediction-rate",
        type=float,
        default=1.0,
        help="Minimum held-out safe prediction rate required for a calibrated operating point to be considered feasible.",
    )
    return parser.parse_args()


def _render_summary_markdown(summary: dict[str, object]) -> str:
    lines = [
        "# Runtime Page Selector Artifact",
        "",
        f"- artifact kind: {summary['artifact_kind']}",
        f"- classes: {int(summary['class_count'])}",
        f"- training examples: {int(summary['train_example_count'])}",
        f"- runtime feature count: {int(summary['feature_count'])}",
        f"- artifact path: {summary['artifact_path']}",
        "",
        "## Features",
        "",
    ]
    if summary["artifact_kind"] == "linear":
        lines[6:6] = [
            f"- class balance exponent: {float(summary['class_balance']):.2f}",
            f"- safe bytes weight: {float(summary['safe_bytes_weight']):.2f}",
            f"- unsafe error weight: {float(summary['unsafe_error_weight']):.2f}",
            f"- reference candidate: {summary['reference_candidate']}",
        ]
    elif summary["artifact_kind"] == "candidate-safe-router":
        lines[6:6] = [
            f"- fallback candidate: {summary['fallback_candidate']}",
            f"- candidate count: {int(summary['candidate_count'])}",
        ]
    for feature_name in summary["feature_names"]:
        lines.append(f"- `{feature_name}`")
    evaluation = summary.get("test_evaluation")
    if isinstance(evaluation, dict):
        lines.extend(
            [
                "",
                "## Held-out Eval",
                "",
                f"- target accuracy: {float(evaluation['target_accuracy']):.3f}",
                f"- safe prediction rate: {float(evaluation['safe_prediction_rate']):.3f}",
                f"- mean safe bytes regret: {float(evaluation['mean_safe_bytes_regret']):.1f}",
                f"- mean predicted total bytes: {float(evaluation['mean_predicted_total_bytes']):.1f}",
            ]
        )
    calibration = summary.get("held_out_calibration")
    if isinstance(calibration, dict) and isinstance(calibration.get("best"), dict):
        best = calibration["best"]
        lines.extend(
            [
                "",
                "## Held-out Calibration",
                "",
                f"- target candidate: {calibration['target_candidate']}",
                f"- feasible subset used: {bool(calibration['used_feasible_subset'])}",
                f"- recommended logit offset: {float(best['logit_offset']):.2f}",
                f"- target accuracy: {float(best['target_accuracy']):.3f}",
                f"- safe prediction rate: {float(best['safe_prediction_rate']):.3f}",
                f"- mean predicted total bytes: {float(best['mean_predicted_total_bytes']):.1f}",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    if args.split_dir is not None:
        split_payload = load_selector_split_examples(split_dir=args.split_dir)
        train_examples = split_payload["train_examples"]
        test_examples = split_payload["test_examples"]
        train_candidate_examples = split_payload["train_candidate_examples"]
        test_candidate_examples = split_payload["test_candidate_examples"]
        split_summary = split_payload["split_summary"]
    else:
        if args.labels is None or args.selector_dataset is None:
            raise SystemExit("--labels and --selector-dataset are required unless --split-dir is provided")
        train_examples = load_selector_examples(labels_path=args.labels, selector_dataset_path=args.selector_dataset)
        test_examples = None
        train_candidate_examples = []
        test_candidate_examples = []
        split_summary = None
        if args.selector_candidate_dataset is not None:
            train_candidate_examples = load_selector_candidate_examples(
                selector_candidate_dataset_path=args.selector_candidate_dataset
            )

    if args.artifact_kind == "candidate-safe-router":
        if not train_candidate_examples:
            raise SystemExit("candidate-safe-router artifacts require candidate examples via --split-dir or --selector-candidate-dataset")
        model = train_candidate_safe_router(
            train_candidate_examples,
            steps=args.steps,
            learning_rate=args.learning_rate,
            l2=args.l2,
        )
        feature_names = model.safe_model.feature_names
        class_count = len(model.candidate_tokens)
    else:
        model = train_runtime_linear_selector(
            train_examples,
            steps=args.steps,
            learning_rate=args.learning_rate,
            l2=args.l2,
            class_balance=args.class_balance,
            safe_bytes_weight=args.safe_bytes_weight,
            unsafe_error_weight=args.unsafe_error_weight,
            reference_candidate=args.reference_candidate,
        )
        feature_names = model.feature_names
        class_count = len(model.classes)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifact_filename = "candidate_safe_router_model.json" if args.artifact_kind == "candidate-safe-router" else "linear_selector_model.json"
    artifact_path = output_dir / artifact_filename
    summary_path = output_dir / "selector_artifact_summary.json"
    markdown_path = output_dir / "selector_artifact_summary.md"
    save_page_selector_artifact(model, artifact_path)

    summary: dict[str, object] = {
        "artifact_kind": str(args.artifact_kind),
        "artifact_path": str(artifact_path),
        "train_example_count": len(train_examples),
        "class_count": int(class_count),
        "feature_count": len(feature_names),
        "feature_names": list(feature_names),
        "runtime_feature_names": list(RUNTIME_SELECTOR_FEATURE_NAMES),
        "steps": int(args.steps),
        "learning_rate": float(args.learning_rate),
        "l2": float(args.l2),
    }
    if args.artifact_kind == "candidate-safe-router":
        assert hasattr(model, "candidate_tokens")
        summary["classes"] = list(model.candidate_tokens)
        summary["candidate_count"] = len(model.candidate_tokens)
        summary["fallback_candidate"] = model.fallback_candidate
    else:
        summary["classes"] = list(model.classes)
        summary["class_balance"] = float(args.class_balance)
        summary["safe_bytes_weight"] = float(args.safe_bytes_weight)
        summary["unsafe_error_weight"] = float(args.unsafe_error_weight)
        summary["reference_candidate"] = str(args.reference_candidate)
    if split_summary is not None:
        summary["split_summary"] = split_summary
    if test_examples is not None:
        if args.artifact_kind == "candidate-safe-router":
            if not test_candidate_examples:
                raise SystemExit("candidate-safe-router split evaluation requires test candidate examples")
            evaluation = evaluate_candidate_safe_router_model(model, test_candidate_examples).to_dict()
        else:
            evaluation = evaluate_selector_model(model, test_examples).to_dict()
        evaluation.pop("predictions", None)
        summary["test_example_count"] = len(test_examples)
        summary["test_evaluation"] = evaluation
        if args.artifact_kind == "linear" and args.calibration_offsets:
            summary["held_out_calibration"] = calibrate_selector_logit_offset(
                model,
                test_examples,
                target_candidate=args.calibration_target_candidate,
                offsets=args.calibration_offsets,
                min_target_accuracy=args.calibration_min_target_accuracy,
                min_safe_prediction_rate=args.calibration_min_safe_prediction_rate,
            )

    summary_path.write_text(json.dumps(summary, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(_render_summary_markdown(summary), encoding="utf-8")
    print(artifact_path)
    print(summary_path)
    print(markdown_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
