#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from dotcache.selector_baselines import (
    RUNTIME_SELECTOR_FEATURE_NAMES,
    evaluate_selector_model,
    load_selector_examples,
    load_selector_split_examples,
    save_linear_selector_model,
    train_runtime_linear_selector,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a runtime-safe learned page-selector artifact for serving.")
    parser.add_argument(
        "--split-dir",
        default=None,
        help="Optional frozen split directory containing train/ and test/ bundles. If provided, trains on train/ and evaluates on test/.",
    )
    parser.add_argument("--labels", default=None, help="Path to labels.jsonl generated by generate_page_oracle_labels.py.")
    parser.add_argument(
        "--selector-dataset",
        default=None,
        help="Path to selector_dataset.jsonl generated by generate_page_oracle_labels.py.",
    )
    parser.add_argument("--output-dir", required=True, help="Directory where the selector artifact and summaries should be written.")
    parser.add_argument("--steps", type=int, default=400)
    parser.add_argument("--learning-rate", type=float, default=0.2)
    parser.add_argument("--l2", type=float, default=1e-3)
    return parser.parse_args()


def _render_summary_markdown(summary: dict[str, object]) -> str:
    lines = [
        "# Runtime Page Selector Artifact",
        "",
        f"- classes: {int(summary['class_count'])}",
        f"- training examples: {int(summary['train_example_count'])}",
        f"- runtime feature count: {int(summary['feature_count'])}",
        f"- artifact path: {summary['artifact_path']}",
        "",
        "## Features",
        "",
    ]
    for feature_name in summary["feature_names"]:
        lines.append(f"- `{feature_name}`")
    evaluation = summary.get("test_evaluation")
    if isinstance(evaluation, dict):
        lines.extend(
            [
                "",
                "## Held-out Eval",
                "",
                f"- target accuracy: {float(evaluation['target_accuracy']):.3f}",
                f"- safe prediction rate: {float(evaluation['safe_prediction_rate']):.3f}",
                f"- mean safe bytes regret: {float(evaluation['mean_safe_bytes_regret']):.1f}",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()
    if args.split_dir is not None:
        split_payload = load_selector_split_examples(split_dir=args.split_dir)
        train_examples = split_payload["train_examples"]
        test_examples = split_payload["test_examples"]
        split_summary = split_payload["split_summary"]
    else:
        if args.labels is None or args.selector_dataset is None:
            raise SystemExit("--labels and --selector-dataset are required unless --split-dir is provided")
        train_examples = load_selector_examples(labels_path=args.labels, selector_dataset_path=args.selector_dataset)
        test_examples = None
        split_summary = None

    model = train_runtime_linear_selector(
        train_examples,
        steps=args.steps,
        learning_rate=args.learning_rate,
        l2=args.l2,
    )

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifact_path = output_dir / "linear_selector_model.json"
    summary_path = output_dir / "selector_artifact_summary.json"
    markdown_path = output_dir / "selector_artifact_summary.md"
    save_linear_selector_model(model, artifact_path)

    summary: dict[str, object] = {
        "artifact_path": str(artifact_path),
        "train_example_count": len(train_examples),
        "class_count": len(model.classes),
        "classes": list(model.classes),
        "feature_count": len(model.feature_names),
        "feature_names": list(model.feature_names),
        "runtime_feature_names": list(RUNTIME_SELECTOR_FEATURE_NAMES),
        "steps": int(args.steps),
        "learning_rate": float(args.learning_rate),
        "l2": float(args.l2),
    }
    if split_summary is not None:
        summary["split_summary"] = split_summary
    if test_examples is not None:
        evaluation = evaluate_selector_model(model, test_examples).to_dict()
        evaluation.pop("predictions", None)
        summary["test_example_count"] = len(test_examples)
        summary["test_evaluation"] = evaluation

    summary_path.write_text(json.dumps(summary, sort_keys=True, indent=2) + "\n", encoding="utf-8")
    markdown_path.write_text(_render_summary_markdown(summary), encoding="utf-8")
    print(artifact_path)
    print(summary_path)
    print(markdown_path)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
